apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellospring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellospring
  template:
    metadata:
      labels:
        app: hellospring
    spec:
      containers:
      - name: hellospring
        image: us-central1-docker.pkg.dev/buoyant-program-452814-d6/cloud-build-samples/hellospring
      ports:
      - containerPort: 8080
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
